//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный текст был создан автоматически: Microsoft.VSDesigner, версия: 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace OZW772_RMU720.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IDataService", Namespace="http://tempuri.org/")]
    public partial class DataService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback PostWriteValueHttpsOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitOperationCompleted;
        
        private System.Threading.SendOrPostCallback StartUpdatingOperationCompleted;
        
        private System.Threading.SendOrPostCallback StopUpdatingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataService() {
            this.Url = global::OZW772_RMU720.Properties.Settings.Default.OZW772_RMU720_localhost_DataService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event PostWriteValueHttpsCompletedEventHandler PostWriteValueHttpsCompleted;
        
        /// <remarks/>
        public event InitCompletedEventHandler InitCompleted;
        
        /// <remarks/>
        public event StartUpdatingCompletedEventHandler StartUpdatingCompleted;
        
        /// <remarks/>
        public event StopUpdatingCompletedEventHandler StopUpdatingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDataService/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/MasterSCADAWindowsService")]
        public SCADAObject[] GetData([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sessionIP, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestObject requestObject) {
            object[] results = this.Invoke("GetData", new object[] {
                        sessionIP,
                        requestObject});
            return ((SCADAObject[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(string sessionIP, RequestObject requestObject) {
            this.GetDataAsync(sessionIP, requestObject, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(string sessionIP, RequestObject requestObject, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        sessionIP,
                        requestObject}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDataService/PostWriteValueHttps", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostWriteValueHttps([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sessionIP, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestObject requestObject, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string id, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string new_value, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ip) {
            object[] results = this.Invoke("PostWriteValueHttps", new object[] {
                        sessionIP,
                        requestObject,
                        id,
                        new_value,
                        ip});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PostWriteValueHttpsAsync(string sessionIP, RequestObject requestObject, string id, string new_value, string ip) {
            this.PostWriteValueHttpsAsync(sessionIP, requestObject, id, new_value, ip, null);
        }
        
        /// <remarks/>
        public void PostWriteValueHttpsAsync(string sessionIP, RequestObject requestObject, string id, string new_value, string ip, object userState) {
            if ((this.PostWriteValueHttpsOperationCompleted == null)) {
                this.PostWriteValueHttpsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostWriteValueHttpsOperationCompleted);
            }
            this.InvokeAsync("PostWriteValueHttps", new object[] {
                        sessionIP,
                        requestObject,
                        id,
                        new_value,
                        ip}, this.PostWriteValueHttpsOperationCompleted, userState);
        }
        
        private void OnPostWriteValueHttpsOperationCompleted(object arg) {
            if ((this.PostWriteValueHttpsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PostWriteValueHttpsCompleted(this, new PostWriteValueHttpsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDataService/Init", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Init([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sessionIP, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestObject requestObjects) {
            this.Invoke("Init", new object[] {
                        sessionIP,
                        requestObjects});
        }
        
        /// <remarks/>
        public void InitAsync(string sessionIP, RequestObject requestObjects) {
            this.InitAsync(sessionIP, requestObjects, null);
        }
        
        /// <remarks/>
        public void InitAsync(string sessionIP, RequestObject requestObjects, object userState) {
            if ((this.InitOperationCompleted == null)) {
                this.InitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitOperationCompleted);
            }
            this.InvokeAsync("Init", new object[] {
                        sessionIP,
                        requestObjects}, this.InitOperationCompleted, userState);
        }
        
        private void OnInitOperationCompleted(object arg) {
            if ((this.InitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDataService/StartUpdating", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StartUpdating([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sessionIP, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestObject requestObjects) {
            this.Invoke("StartUpdating", new object[] {
                        sessionIP,
                        requestObjects});
        }
        
        /// <remarks/>
        public void StartUpdatingAsync(string sessionIP, RequestObject requestObjects) {
            this.StartUpdatingAsync(sessionIP, requestObjects, null);
        }
        
        /// <remarks/>
        public void StartUpdatingAsync(string sessionIP, RequestObject requestObjects, object userState) {
            if ((this.StartUpdatingOperationCompleted == null)) {
                this.StartUpdatingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartUpdatingOperationCompleted);
            }
            this.InvokeAsync("StartUpdating", new object[] {
                        sessionIP,
                        requestObjects}, this.StartUpdatingOperationCompleted, userState);
        }
        
        private void OnStartUpdatingOperationCompleted(object arg) {
            if ((this.StartUpdatingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartUpdatingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IDataService/StopUpdating", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StopUpdating([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sessionIP, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] RequestObject requestObjects) {
            this.Invoke("StopUpdating", new object[] {
                        sessionIP,
                        requestObjects});
        }
        
        /// <remarks/>
        public void StopUpdatingAsync(string sessionIP, RequestObject requestObjects) {
            this.StopUpdatingAsync(sessionIP, requestObjects, null);
        }
        
        /// <remarks/>
        public void StopUpdatingAsync(string sessionIP, RequestObject requestObjects, object userState) {
            if ((this.StopUpdatingOperationCompleted == null)) {
                this.StopUpdatingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStopUpdatingOperationCompleted);
            }
            this.InvokeAsync("StopUpdating", new object[] {
                        sessionIP,
                        requestObjects}, this.StopUpdatingOperationCompleted, userState);
        }
        
        private void OnStopUpdatingOperationCompleted(object arg) {
            if ((this.StopUpdatingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StopUpdatingCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MasterSCADAWindowsService")]
    public partial class RequestObject {
        
        private string[] iDsField;
        
        private string[] iDsForRequestsField;
        
        private string uRIField;
        
        private string uRLField;
        
        private string uRLsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] IDs {
            get {
                return this.iDsField;
            }
            set {
                this.iDsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] IDsForRequests {
            get {
                return this.iDsForRequestsField;
            }
            set {
                this.iDsForRequestsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string URLs {
            get {
                return this.uRLsField;
            }
            set {
                this.uRLsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/MasterSCADAWindowsService")]
    public partial class SCADAObject {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SCADAObject[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SCADAObject[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void PostWriteValueHttpsCompletedEventHandler(object sender, PostWriteValueHttpsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostWriteValueHttpsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PostWriteValueHttpsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void InitCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StartUpdatingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StopUpdatingCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591